### ISSUE TITLE
adding valence electrons

### ISSUE THREAD

**Issue by cambo2015** [arpitnarechania/d3-molecule#8]
Hi. I've been making my own version/software with this amazing library. I am trying to write functionality for the octet rule. If an element has 8 electrons then don't allow any more links. I added valence electron property to each element in periodicTableData. I also changed the piece of code to this:
```javascript 
var addNode = function(atom, size, chargeString) {
        alert("adding node")
        console.log(atom)
        parent.maxNodeId += 1;

        const valence = periodicTableData.filter(x=>x.Symbol.toUpperCase()===atom.toUpperCase())[0].Valence_Electrons
        console.log(valence)
        parent.graph.nodes.push({
            "id": parent.maxNodeId,
            "atom": atom,
            "size": size,
            "charge":chargeString,
           "valance_electrons":valence,
           "current_electrons":valence
           
        });
    };
 ```

lastly  I am trying to increment and only allow links if currentElectrons < 8. I looked in the addlink() in Molecule.js but it only returns ids instead of the object itself. This is where I am stuck. Any help would be awesome and greatly appreciated. Here is what I am trying to do:
```javascript
 var addLink = function(source_id, target_id, bond) {
        alert("adding link")
        console.log(parent)
        // get source
        //if (currentElectrons< 8) {
            var source_index = findNodeIndexFromId(source_id);
            var target_index = findNodeIndexFromId(target_id);
            
            var link_object = {
                "source": source_index, //access  the source's currentElectrons property  and ++ 
                "target": target_index,
                "bond": bond,
                
            };
        parent.graph.links.push(link_object);
        // }
    };
```

Thanks

**Comment by arpitnarechania** [comment]
Thanks, it's been a while since I have seen this package; I will take a look over the weekend and get back to you if that's okay.

**Comment by arpitnarechania** [comment]
Hi @cambo2015, so if I understand correctly, all you need is a reference to the corresponding data object from the source_id, right? 

There is a variable, "parent" that holds the entire context of the app. So, you can use `parent.graph.nodes[node_index]` and `parent.graph.links[link_index]` to access specific nodes and links.

Then, you can run a simple for loop:

```
for (var i = 0; i < parent.graph.links.length; i++) {
            if (parent.graph.links[i].source.id == source_id && parent.graph.links[i].target.id == target_id) {
                    // parent.graph.links[i].source is your desired source node
                    // parent.graph.links[i].target is your desired target node
                    
                    // You can then check for valence electrons or any other property through: 
                    // parent.graph.links[i].source.no_of_valence_electrons
            }
}
```

In addition, there is a simpler direct API available:
`findNodeIdFromIndex()` that accepts a node_id (source_id or target_id) and returns the corresponding index within the parent.graph.nodes array. So, all you have to do is

```
let sourceIndex = findNodeIdFromIndex(source_id), and then
let node = parent.graph.nodes[sourceIndex]
console.log(node.no_of_valence_electrons)
```

I hope this helps!! Also, very sorry for the delayed response.

**Comment by cambo2015** [comment]
Awesome! I will try that. Thank you
